import { useState, useEffect } from 'react';
import { api } from '../services/api';
import { motion } from 'framer-motion';
import { jsPDF } from 'jspdf';
import ControlGap from '../components/dashboard/ControlGap';
import RiskTrending from '../components/dashboard/RiskTrending';
import RiskHeatMap from '../components/dashboard/RiskHeatMap';

export default function Dashboard() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadDashboard();
  }, []);

  const loadDashboard = async () => {
    try {
      const result = await api.get('/dashboard');
      setData(result);
    } catch (error) {
      console.error('Failed to load dashboard:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleExportPDF = async () => {
    try {
      const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
      const w = pdf.internal.pageSize.getWidth();
      const h = pdf.internal.pageSize.getHeight();
      const m = 15;
      
      // Header
      pdf.setFillColor(13, 148, 136);
      pdf.rect(0, 0, w, 30, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(22);
      pdf.setFont('helvetica', 'bold');
      pdf.text('VectorRM', m, 20);
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.text('Executive Risk Report', m + 60, 14);
      pdf.text(`Generated: ${new Date().toLocaleDateString()}`, w - m - 30, 14);
      
      let y = 45;
      
      // Executive Summary Box
      pdf.setFillColor(248, 250, 252);
      pdf.roundedRect(m, y, w - m * 2, 35, 3, 3, 'F');
      pdf.setTextColor(30, 30, 30);
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Executive Summary', m + 5, y + 10);
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(80, 80, 80);
      const summary = `This report provides a comprehensive overview of the organization's IT risk posture. Key metrics indicate ${data?.summary?.totalRisks || 0} total risks, with ${data?.summary?.openRisks || 0} requiring immediate attention. Risk mitigation progress is tracked through status categories.`;
      const lines = pdf.splitTextToSize(summary, w - m * 2 - 10);
      pdf.text(lines, m + 5, y + 18);
      
      y += 45;
      
      // KPI Cards
      const cardW = (w - m * 2 - 15) / 4;
      const kpis = [
        { label: 'Total Risks', value: data?.summary?.totalRisks || 0, color: [20, 184, 166] },
        { label: 'Open', value: data?.summary?.openRisks || 0, color: [220, 38, 38] },
        { label: 'Mitigating', value: data?.summary?.mitigatingRisks || 0, color: [217, 119, 6] },
        { label: 'Closed', value: data?.summary?.closedRisks || 0, color: [34, 197, 94] }
      ];
      
      kpis.forEach((kpi, i) => {
        pdf.setFillColor(255, 255, 255);
        pdf.roundedRect(m + i * (cardW + 5), y, cardW, 40, 3, 3, 'F');
        pdf.setDrawColor(229, 231, 235);
        pdf.roundedRect(m + i * (cardW + 5), y, cardW, 40, 3, 3, 'S');
        
        pdf.setTextColor(100, 100, 100);
        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'normal');
        pdf.text(kpi.label, m + i * (cardW + 5) + 5, y + 8);
        
        pdf.setTextColor(kpi.color[0], kpi.color[1], kpi.color[2]);
        pdf.setFontSize(24);
        pdf.setFont('helvetica', 'bold');
        pdf.text(String(kpi.value), m + i * (cardW + 5) + 5, y + 25);
      });
      
      y += 50;
      
      // Footer - Page 1
      pdf.setFillColor(240, 240, 240);
      pdf.rect(0, h - 12, w, 12, 'F');
      pdf.setTextColor(120, 120, 120);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.text('Generated by VectorRM - Enterprise Risk Management Platform', m, h - 5);
      
      // Page 2 - Risk Distribution & Heat Matrix
      pdf.addPage();
      
      // Header on page 2
      pdf.setFillColor(13, 148, 136);
      pdf.rect(0, 0, w, 20, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.text('VectorRM - Risk Analysis', m, 14);
      
      y = 35;
      
      // Risk by Domain
      pdf.setTextColor(30, 30, 30);
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Risk Distribution by Domain', m, y);
      y += 12;
      
      const domainChartData = data?.byDomain || [];
      if (domainChartData.length > 0) {
        const maxCount = Math.max(...domainChartData.map(d => d.count), 1);
        const barMaxHeight = 30;
        const barGap = 5;
        const barWidth = Math.min(30, (w - m * 2 - 20) / Math.max(domainChartData.length, 1));
        
        domainChartData.forEach((domain, i) => {
          const barHeight = (domain.count / maxCount) * barMaxHeight;
          const x = m + i * (barWidth + barGap);
          
          const colors = [[20, 184, 166], [99, 102, 241], [168, 85, 247], [236, 72, 153], [249, 115, 22]];
          const color = colors[i % colors.length];
          pdf.setFillColor(color[0], color[1], color[2]);
          pdf.roundedRect(x, y + barMaxHeight - barHeight, barWidth, barHeight, 2, 2, 'F');
          
          pdf.setTextColor(60, 60, 60);
          pdf.setFontSize(7);
          pdf.setFont('helvetica', 'normal');
          const name = domain.domain.length > 10 ? domain.domain.substring(0, 8) + '..' : domain.domain;
          pdf.text(name, x + barWidth / 2, y + barMaxHeight + 6, { align: 'center' });
          pdf.text(String(domain.count), x + barWidth / 2, y + barMaxHeight + 12, { align: 'center' });
        });
      }
      
      y += 55;
      
      // Heat Matrix
      pdf.setTextColor(30, 30, 30);
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Risk Heat Matrix', m, y);
      y += 10;
      
      const heatMapData = data?.heatMap || [];
      const cellSize = 14;
      
      // Draw axis numbers
      pdf.setTextColor(100, 100, 100);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      
      // Impact numbers (top, across columns)
      for (let i = 1; i <= 5; i++) {
        pdf.text(String(i), m + 35 + (i - 1) * cellSize, y + 5, { align: 'center' });
      }
      
      // Likelihood numbers (left, down rows)
      for (let i = 1; i <= 5; i++) {
        pdf.text(String(i), m + 20, y + 10 + (i - 1) * cellSize + cellSize / 2, { align: 'right' });
      }
      
      // Axis labels
      pdf.text('Impact →', m + 85, y - 2);
      pdf.text('Likelihood ↓', m - 2, y + 40);
      
      for (let li = 0; li < 5; li++) {
        for (let im = 0; im < 5; im++) {
          const cell = heatMapData.find(c => c.likelihood === li + 1 && c.impact === im + 1);
          const count = cell?.count || 0;
          const risk = (li + 1) * (im + 1);
          
          let color;
          if (risk >= 15) color = [220, 38, 38];
          else if (risk >= 8) color = [234, 179, 8];
          else color = [34, 197, 94];
          
          if (count > 0) {
            pdf.setFillColor(color[0], color[1], color[2]);
            pdf.roundedRect(m + 30 + im * cellSize, y + 10 + li * cellSize, cellSize - 1, cellSize - 1, 1, 1, 'F');
            pdf.setTextColor(255, 255, 255);
            pdf.setFontSize(8);
            pdf.setFont('helvetica', 'bold');
            pdf.text(String(count), m + 30 + im * cellSize + cellSize / 2, y + 10 + li * cellSize + cellSize / 2 + 1, { align: 'center' });
          } else {
            pdf.setFillColor(240, 240, 240);
            pdf.roundedRect(m + 30 + im * cellSize, y + 10 + li * cellSize, cellSize - 1, cellSize - 1, 1, 1, 'F');
          }
        }
      }
       
      // Footer
      pdf.setFillColor(240, 240, 240);
      pdf.rect(0, h - 12, w, 12, 'F');
      pdf.setTextColor(120, 120, 120);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.text('Generated by VectorRM - Enterprise Risk Management Platform', m, h - 5);
      
      pdf.save(`Risk-Report-${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
      console.error('PDF export failed:', error);
      alert('Failed to export PDF: ' + error.message);
    }
  };

  if (loading) {
    return (
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {[...Array(8)].map((_, i) => (
          <div key={i} className="h-32 bg-gray-200 dark:bg-slate-700 rounded-2xl animate-pulse"></div>
        ))}
      </div>
    );
  }

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const item = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0 }
  };

  return (
    <motion.div
      variants={container}
      initial="hidden"
      animate="show"
      className="space-y-6"
      id="dashboard-content"
    >
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-2xl font-semibold text-gray-900 dark:text-white">Risk Dashboard</h1>
          <p className="text-gray-500 dark:text-slate-400 mt-1">Enterprise risk overview and key metrics</p>
        </div>
        <button
          onClick={handleExportPDF}
          className="flex items-center gap-2 px-4 py-2 rounded-xl bg-white dark:bg-slate-800 border border-gray-200 dark:border-slate-700 text-gray-700 dark:text-slate-300 hover:bg-gray-50 dark:hover:bg-slate-700"
        >
          <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
          </svg>
          Export PDF
        </button>
      </div>

      <motion.div variants={item} className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 shadow-card">
          <p className="text-sm font-medium text-gray-500 dark:text-slate-400">Total Risks</p>
          <p className="text-3xl font-bold text-gray-900 dark:text-white mt-2">{data?.summary?.totalRisks || 0}</p>
          <p className="text-xs text-gray-400 dark:text-slate-500 mt-2">Across all domains</p>
        </div>

        <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 shadow-card">
          <p className="text-sm font-medium text-gray-500 dark:text-slate-400">Open Risks</p>
          <p className="text-3xl font-bold text-red-600 mt-2">{data?.summary?.openRisks || 0}</p>
          <p className="text-xs text-gray-400 dark:text-slate-500 mt-2">Requiring attention</p>
        </div>

        <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 shadow-card">
          <p className="text-sm font-medium text-gray-500 dark:text-slate-400">Mitigating</p>
          <p className="text-3xl font-bold text-amber-600 mt-2">{data?.summary?.mitigatingRisks || 0}</p>
          <p className="text-xs text-gray-400 dark:text-slate-500 mt-2">Controls in progress</p>
        </div>

        <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 shadow-card">
          <p className="text-sm font-medium text-gray-500 dark:text-slate-400">Closed</p>
          <p className="text-3xl font-bold text-green-600 mt-2">{data?.summary?.closedRisks || 0}</p>
          <p className="text-xs text-gray-400 dark:text-slate-500 mt-2">Successfully addressed</p>
        </div>
      </motion.div>

      <motion.div variants={item} className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 shadow-card">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Control Gap</h3>
          <ControlGap percentage={data?.summary?.controlGap || 0} />
        </div>

        <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 shadow-card lg:col-span-2">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Risk Distribution</h3>
          <div className="flex items-center gap-8">
            <div className="flex-1">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-3 h-3 rounded-full bg-red-500"></div>
                    <span className="text-sm text-gray-600 dark:text-slate-400">High Risk (15-25)</span>
                  </div>
                  <span className="font-semibold text-gray-900 dark:text-white">{data?.summary?.highRisks || 0}</span>
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-3 h-3 rounded-full bg-amber-500"></div>
                    <span className="text-sm text-gray-600 dark:text-slate-400">Medium Risk (6-14)</span>
                  </div>
                  <span className="font-semibold text-gray-900 dark:text-white">{data?.summary?.mediumRisks || 0}</span>
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-3 h-3 rounded-full bg-green-500"></div>
                    <span className="text-sm text-gray-600 dark:text-slate-400">Low Risk (1-5)</span>
                  </div>
                  <span className="font-semibold text-gray-900 dark:text-white">{data?.summary?.lowRisks || 0}</span>
                </div>
              </div>
            </div>
            <div className="w-32 h-32 relative">
              <svg className="w-full h-full transform -rotate-90">
                <circle cx="64" cy="64" r="56" stroke="#e2e8f0" strokeWidth="12" fill="none" className="dark:stroke-slate-700" />
                <circle
                  cx="64"
                  cy="64"
                  r="56"
                  stroke="#14b8a6"
                  strokeWidth="12"
                  fill="none"
                  strokeDasharray={`${(data?.summary?.highRisks / data?.summary?.totalRisks) * 352 || 0} 352`}
                  strokeLinecap="round"
                />
              </svg>
            </div>
          </div>
        </div>
      </motion.div>

      <motion.div variants={item} className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="space-y-6">
          <RiskTrending data={data?.byDomain || []} />
        </div>
        <RiskHeatMap data={data?.heatMap || []} />
      </motion.div>
    </motion.div>
  );
}
